### ISSUE TITLE
Сменить названия файлов печатных форм на удобные

### ISSUE THREAD

**Issue by dskarataev** [odoo-russia/odoo-russia#3]
Сейчас при скачивании печатных форм имя PDF файла называется просто названием типа печатной формы, как он указан в выпадающем списке по кнопке Печать, т.е. названия у всех счетов одинаковые - просто "Счёт".

Было бы намного удобнее, чтобы в названиях печатных форм также фигурировал номер документа, дата документа и партнер.

Примеры:
"Счет № 127 от 12.09.2013 для Велвекс" (сюда подставляем не официальное наименование а обычное - то что в поле name в res.partner)
"ТОРГ-12 № 256 от 12.09.2013 для Велвекс"
"Счет-фактура № 222 от 12.09.2013 для Велвекс"

и так далее.

**Comment by dskarataev** [comment]
Счёт №32 от 2013-09-25 для НОХТ.pdf

@ivkond формат даты не совпадает с примером, приведенным в задаче. Нужно переделать на дд.мм.ГГГГ

**Comment by dskarataev** [comment]
@ivkond при нажатии красной кнопки Печать в Sale Order выдается такая ошибка:

``` python
Client Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/http.py", line 285, in dispatch
    r = method(self, **self.params)
  File "/home/dsk/git/openerp/modules/tt_print_forms_names/controllers/report_controller.py", line 95, in index
    res_id[0] = res_id[1]
IndexError: list index out of range
```

**Comment by dskarataev** [comment]
@ivkond ошибка при нажатии на кнопку Печать пропала после перезапуска сервиса OpenERP. Ошибка с форматом даты остается.

**Comment by dskarataev** [comment]
стабильная версия в коммите a5571457f03fdf1a3327c4c4c9d25e45871f57f7
